### ISSUE TITLE
Failed after restart 

### ISSUE THREAD

**Issue by igreenfield** [nemwiz/jira-commit-message-intellij-plugin#22] opened 2021-04-19 06:29 UTC
When branch is master I see that error when intellij starts:

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at com.intellij.util.SmartList.checkOutOfBounds(SmartList.java:66)
	at com.intellij.util.SmartList.get(SmartList.java:57)
	at org.nemwiz.jiracommitmessage.services.MyProjectService.getTaskIdFromBranchName(MyProjectService.kt:17)
	at org.nemwiz.jiracommitmessage.provider.PluginProvider.getCommitMessage(PluginProvider.kt:13)
	at com.intellij.vcs.commit.AbstractCommitMessagePolicy.getCommitMessageFor(AbstractCommitMessagePolicy.kt:24)
	at com.intellij.vcs.commit.ChangesViewCommitMessagePolicy.getCommitMessage(ChangesViewCommitMessagePolicy.kt:11)
	at com.intellij.vcs.commit.ChangesViewCommitWorkflowHandler.getCommitMessageFromPolicy(ChangesViewCommitWorkflowHandler.kt:194)
	at com.intellij.vcs.commit.ChangesViewCommitWorkflowHandler.changeListChanged(ChangesViewCommitWorkflowHandler.kt:185)
	at com.intellij.vcs.commit.ChangesViewCommitWorkflowHandler.access$changeListChanged(ChangesViewCommitWorkflowHandler.kt:23)
	at com.intellij.vcs.commit.ChangesViewCommitWorkflowHandler$$special$$inlined$observable$1.afterChange(Delegates.kt:72)
	at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
	at com.intellij.vcs.commit.ChangesViewCommitWorkflowHandler.setCurrentChangeList(ChangesViewCommitWorkflowHandler.kt)
	at com.intellij.vcs.commit.ChangesViewCommitWorkflowHandler.<init>(ChangesViewCommitWorkflowHandler.kt:80)
	at com.intellij.openapi.vcs.changes.ChangesViewManager$ChangesViewToolWindowPanel.updateCommitWorkflow(ChangesViewManager.java:577)
	at com.intellij.openapi.vcs.changes.ChangesViewManager.updateCommitWorkflow(ChangesViewManager.java:272)
	at com.intellij.openapi.vcs.changes.ChangesViewManager.lambda$new$0(ChangesViewManager.java:116)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:671)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:649)
	at com.intellij.util.messages.impl.MessageBusImpl.access$300(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.executeOrAddToQueue(MessageBusImpl.java:215)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.publish(MessageBusImpl.java:197)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:181)
	at com.sun.proxy.$Proxy132.commitModeChanged(Unknown Source)
	at com.intellij.vcs.commit.CommitModeManager.updateCommitMode(CommitModeManager.kt:75)
	at com.intellij.vcs.commit.CommitModeManager$MyStartupActivity$runActivity$$inlined$runInEdt$1.run(actions.kt:64)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by nemwiz** [comment] 2021-04-19 11:43
Hi @igreenfield 

As mentioned in the previous issue that you opened, I would need more information in order to fix this bug.
Which version of IntelliJ are you using and which version of the plugin?

When does this error occur and does it crash your IntelliJ or?

Thanks

**Comment by igreenfield** [comment] 2021-04-19 16:56
- Which version of IntelliJ are you using?

```
IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
```

- Which version of the plugin are you using?
2.1.1

- Operating system
Windows 10

- How do you know that this line is causing the issue?
 from the stacktrace in idea report issue window

- When does this error occur and does it crash your IntelliJ or?
When I start idea, and idea write it failed to save configuration

**Comment by nemwiz** [comment] 2021-04-19 23:34
I'm still unable to reproduce this bug.

Would it be possible to share the repository that you are using?

Also can you confirm that you've configured the plugin correctly in the IntelliJ settings? `JIRA project prefix` should not be empty.
Instructions can be found on the [main page](https://github.com/nemwiz/jira-commit-message-intellij-plugin).

**Comment by igreenfield** [comment] 2021-04-20 17:20
I configure it according to the instruction still the same. It is internal repo on bitbucket so I can't share it.

**Comment by nemwiz** [comment] 2021-04-21 12:16
I tried a few things, but I don't get the error that you are seeing.
For me the `master` branch returns an empty string which is expected behavior.

So for you the plugin is not working for other branches as well e.g. `feature/PROJECT-PREFIX-123`?

I suspect that it might be due to your repo or some setting inside IntelliJ. 
Could you export me your settings and attach them here? Maybe that helps in finding the issue.
Here is how you can export the settings.
https://www.jetbrains.com/help/idea/sharing-your-ide-settings.html

**Comment by igreenfield** [comment] 2021-04-22 05:41
for other branches, it works.
I will try to export my settings,

**Comment by nemwiz** [comment] 2022-05-19 06:58
Closing this since unable to reproduce and more details weren't provided.

**Closed as completed by nemwiz** 2022-05-19 06:58 UTC
