### ISSUE TITLE
Plugin does nog work in Intellij 2021.3 (and later)

### ISSUE THREAD

**Issue by yeronimuz** [nemwiz/jira-commit-message-intellij-plugin#46] opened 2022-05-16 07:22 UTC
**Describe the bug**
The plugin throws a PatternSyntaxException when invoked on Intellij

**To Reproduce**
1. Install plugin
2. Commit changes to a branche
3. Click on the commit id button
4. See error in additional context below

**Expected behavior**
Jira issue should show up in commit message window

**Screenshots**
-

**System version (please complete the following information):**
 - IntelliJ version: 2021.3 Ultimate Edition
 - Plugin version: 3.11
 - OS: Windows 10

**Additional context**
java.util.regex.PatternSyntaxException: Dangling meta character '+' near index 0
+-[0-9]+
^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2202)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
	at org.nemwiz.jiracommitmessage.services.MyProjectService.matchBranchNameThroughRegex(MyProjectService.kt:36)
	at org.nemwiz.jiracommitmessage.services.MyProjectService.getTaskIdFromBranchName(MyProjectService.kt:18)
	at org.nemwiz.jiracommitmessage.provider.PluginProvider.getCommitMessage(PluginProvider.kt:13)
	at com.intellij.vcs.commit.AbstractCommitMessagePolicy.getCommitMessageFor(AbstractCommitMessagePolicy.kt:24)
	at com.intellij.vcs.commit.ChangesViewCommitMessagePolicy.getCommitMessage(ChangesViewCommitMessagePolicy.kt:11)
	at com.intellij.vcs.commit.ChangesViewCommitWorkflowHandler.getCommitMessageFromPolicy(ChangesViewCommitWorkflowHandler.kt:194)
	at com.intellij.vcs.commit.ChangesViewCommitWorkflowHandler.getCommitMessageFromPolicy$default(ChangesViewCommitWorkflowHandler.kt:191)
	at com.intellij.vcs.commit.ChangesViewCommitWorkflowHandler$GitCommitStateCleaner.initCommitMessage(ChangesViewCommitWorkflowHandler.kt:278)
	at com.intellij.vcs.commit.ChangesViewCommitWorkflowHandler$GitCommitStateCleaner.onSuccess(ChangesViewCommitWorkflowHandler.kt:281)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy387.onSuccess(Unknown Source)
	at com.intellij.vcs.commit.EdtCommitResultHandler$onSuccess$$inlined$runInEdt$1.run(actions.kt:60)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by nemwiz** [comment] 2022-05-17 12:31
Hi @yeronimuz ,

Thank you for reporting this issue. Have you configured your Jira prefix under Settings > Tools  > JIRA Id Commit Message?
Could you please set this and try again?
If this is the reason for failure, I definitely need to improve the error handling and the error message.

**Comment by nemwiz** [comment] 2022-05-19 06:55
I was able to reproduce the issue and as specified above the error is thrown due to a missing configuration.
This is now fixed and released in v2.1.5. Instead of an error, a notification will pop up prompting you to set the Jira prefix.
I'll close this issue. Thanks

**Closed as completed by nemwiz** 2022-05-19 06:55 UTC

**Comment by yeronimuz** [comment] 2022-05-19 08:54
I can confirm that it now works well, thank you.

**Comment by nemwiz** [comment] 2022-05-24 01:16
Thank you for reporting the issue. If you enjoy the plugin, please leave a review at Intellij website. Any feedback is appreciated.
https://plugins.jetbrains.com/plugin/14310-jira-id-commit-message
